import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Video } from 'lucide-react';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getLocale } from 'next-intl/server';
import { ClientProvider } from './client-provider';
import { ConfigProvider } from 'antd';
import idID from 'antd/locale/id_ID';
import enUS from 'antd/locale/en_US';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Sinih',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const messages = await getMessages();
    const locale = await getLocale();
    const currentLocale = locale === 'id' ? idID : enUS;

    return (
        <html lang="id" className="scroll-smooth">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="flex flex-col min-h-screen">
                    <ClientProvider locale={locale}>
                        <NextIntlClientProvider messages={messages}>
                            <ConfigProvider locale={currentLocale}>{children}</ConfigProvider>
                        </NextIntlClientProvider>
                    </ClientProvider>

                    <footer className="border-t border-gray-200 bg-background px-6">
                        <div className="flex flex-col items-center justify-between gap-4 py-10 md:flex-row">
                            <div className="flex flex-col items-center gap-4 px-8 md:flex-row md:gap-2 md:px-0">
                                <Video className="text-primary-600" />
                                <p className="text-center text-sm leading-loose text-muted-foreground md:text-left">
                                    © 2025 Sinih. Semua hak dilindungi.
                                </p>
                            </div>
                            <div className="flex gap-4">
                                <a
                                    className="text-sm text-muted-foreground hover:underline"
                                    href="#"
                                >
                                    Ketentuan
                                </a>
                                <a
                                    className="text-sm text-muted-foreground hover:underline"
                                    href="#"
                                >
                                    Privacy
                                </a>
                                <a
                                    className="text-sm text-muted-foreground hover:underline"
                                    href="#"
                                >
                                    Tentang
                                </a>
                                <a
                                    className="text-sm text-muted-foreground hover:underline"
                                    href="#"
                                >
                                    Kontak
                                </a>
                            </div>
                        </div>
                    </footer>
                </div>
            </body>
        </html>
    );
}
